project:
  type: website

website:
  title: "Real Estate Pricing Analysis in NYC"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    dark-mode: true
    css: styles.css
    toc: true
    page-layout: full



